/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosventanas;

/**
 *
 * @author camil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Ejercicios Semana 3");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inter2 = new javax.swing.JButton();
        inter1 = new javax.swing.JButton();
        inter4 = new javax.swing.JButton();
        inter3 = new javax.swing.JButton();
        inter5 = new javax.swing.JButton();

        jButton3.setText("Interfaz 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ejercicios Interfaces");

        inter2.setText("Interfaz 2");
        inter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inter2ActionPerformed(evt);
            }
        });

        inter1.setText("Interfaz 1");
        inter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inter1ActionPerformed(evt);
            }
        });

        inter4.setText("Interfaz 4");
        inter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inter4ActionPerformed(evt);
            }
        });

        inter3.setText("Interfaz 3");
        inter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inter3ActionPerformed(evt);
            }
        });

        inter5.setText("Interfaz 5");
        inter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inter5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inter2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inter3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inter4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inter5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inter1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(inter1)
                .addGap(18, 18, 18)
                .addComponent(inter2)
                .addGap(18, 18, 18)
                .addComponent(inter3)
                .addGap(18, 18, 18)
                .addComponent(inter4)
                .addGap(18, 18, 18)
                .addComponent(inter5)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inter2ActionPerformed
        Ventana2 obj1 = new Ventana2();
        obj1.setVisible(true);
    }//GEN-LAST:event_inter2ActionPerformed

    private void inter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inter1ActionPerformed
        Ventana1 obj1 = new Ventana1();
        obj1.setVisible(true);
    }//GEN-LAST:event_inter1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Ventana3 obj1 = new Ventana3();
        obj1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inter4ActionPerformed
        Ventana4 obj1 = new Ventana4();
        obj1.setVisible(true);
    }//GEN-LAST:event_inter4ActionPerformed

    private void inter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inter3ActionPerformed
        Ventana3 obj1 = new Ventana3();
        obj1.setVisible(true);
    }//GEN-LAST:event_inter3ActionPerformed

    private void inter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inter5ActionPerformed
        Ventana5 obj1 = new Ventana5();
        obj1.setVisible(true);
    }//GEN-LAST:event_inter5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inter1;
    private javax.swing.JButton inter2;
    private javax.swing.JButton inter3;
    private javax.swing.JButton inter4;
    private javax.swing.JButton inter5;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
